# Generated by Django 5.2.4 on 2025-07-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('vw_golf_vii', 'VW Golf VII'), ('audi_a1_sline', 'Audi A1 S-Line'), ('toyota_camry', 'Toyota Camry'), ('bmw_320_modernline', 'BMW 320 ModernLine')], max_length=50)),
                ('pick_up_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('drop_off_date', models.DateField()),
                ('drop_off_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
