# Generated by Django 5.2.4 on 2025-07-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreservation',
            name='car_type',
            field=models.CharField(choices=[('', 'Select your Car type'), ('VW Golf VII', 'VW Golf VII'), ('Audi A1 S-Line', 'Audi A1 S-Line'), ('Toyota Camry', 'Toyota Camry'), ('BMW 320 ModernLine', 'BMW 320 ModernLine')], max_length=50),
        ),
    ]
