# Generated by Django 5.2.4 on 2025-07-21 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_carreservation_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreservation',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
