# Generated by Django 5.2.4 on 2025-08-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('airport', 'Airport'), ('point_to_point', 'Point To Point'), ('hourly', 'Hourly'), ('frederick', 'Frederick Special Services')], max_length=50)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('dropoff_address', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('passengers', models.PositiveIntegerField()),
                ('luggage', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
