# Generated by Django 5.2.4 on 2025-08-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_booking_alter_carreservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
