# Generated by Django 5.2.4 on 2025-08-17 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_carreservation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('', 'Select your Car type'), ('VW Golf VII', 'VW Golf VII'), ('Audi A1 S-Line', 'Audi A1 S-Line'), ('Toyota Camry', 'Toyota Camry'), ('BMW 320 ModernLine', 'BMW 320 ModernLine')], max_length=50)),
                ('pick_up_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('drop_off_date', models.DateField()),
                ('drop_off_time', models.TimeField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='CarReservation',
        ),
    ]
