# Generated by Django 5.2.4 on 2025-08-18 06:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_reservation_delete_booking_delete_carreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='drop_off_location',
            new_name='pickup',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='drop_off_date',
            new_name='pickup_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='drop_off_time',
            new_name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pick_up_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pick_up_location',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pick_up_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='child_seat',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='reservation',
            name='child_seat_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dropoff',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='flight_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='luggage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='passengers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_dropoff',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_pickup',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_type',
            field=models.CharField(choices=[('point_to_point', 'Point to Point'), ('round_trip', 'Round Trip'), ('hourly', 'Hourly')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle_class',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('luxury', 'Luxury')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='wait_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('', 'Select your Car type'), ('VW Golf VII', 'VW Golf VII'), ('Audi A1 S-Line', 'Audi A1 S-Line'), ('Toyota Camry', 'Toyota Camry'), ('BMW 320 ModernLine', 'BMW 320 ModernLine')], max_length=50)),
                ('pick_up_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('drop_off_date', models.DateField()),
                ('drop_off_time', models.TimeField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
