# Generated by Django 5.2.4 on 2025-08-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0009_rename_drop_off_location_reservation_pickup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_class', models.CharField(max_length=50)),
                ('passengers', models.PositiveIntegerField()),
                ('luggage', models.PositiveIntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='fleet/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxi.fleetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FleetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fleet/gallery/')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='taxi.fleet')),
            ],
        ),
    ]
