# Generated by Django 5.2.4 on 2025-09-04 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0012_alter_carreservation_email_alter_carreservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreservation',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
