# Generated by Django 5.2.4 on 2025-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0013_carreservation_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location_type', models.CharField(choices=[('area', 'Area'), ('airport', 'Airport')], max_length=20)),
            ],
        ),
    ]
